### ISSUE TITLE
Плавающий тест

### ISSUE THREAD

**Issue by nickkkcc** [polis-vk/2023-nosql-lsm#49]
Плавающий тест (иногда проходит, иногда валится).
`Log`:

> BasicConcurrentTest > testConcurrentRead_10_000(Dao) > [1] TestDao<`name_dao_implementation`> FAILED
    java.util.concurrent.TimeoutException at TimeoutInvocation.java:70

**Comment by incubos** [comment]
Поднял таймаут до 10 секунд. Воспроизводится?
