### ISSUE TITLE
HW2 Не работающие тесты на Windows

### ISSUE THREAD

**Issue by alexnevskiy** [polis-vk/2023-nosql-lsm#84]
Не проходят тесты на ОС Windows для второго домашнего задания. Падают с ошибкой "отказано в доступе" при удалении ssTable во временной директории.
![изображение](https://github.com/polis-vk/2023-nosql-lsm/assets/43075975/7a271664-64eb-4ad5-afe5-e17dbb5d72af)

На системах семейства UNIX все тесты проходят успешно (прогонял тесты конкретно на Ubuntu 22.04).
![image_2023-10-01_22-51-53](https://github.com/polis-vk/2023-nosql-lsm/assets/43075975/7e81124f-ed8e-4f37-bddc-ad8080495517)

**Comment by nickkkcc** [comment]
Дело в том, что ребята с Linux работают в папках, в которых их пользователь имеет права на запись, либо через sudo. Кажется, что твой пользователь не является владельцем этой папки и файлов внутри нее. Попробуй ***[это](https://windowsreport.com/access-is-denied-windows-10/)***.

**Comment by incubos** [comment]
Обсудили на занятии, что тестируем всё на Linux (нативно, виртуалки или контейнеры) -- максимально близко к целевому окружению.
